### ISSUE TITLE
Getting critical error message while translating posts

### ISSUE THREAD

**Issue by primeabhishek** [polylang/polylang#1302]
I just tried the plugin, It works fine on pages. But when I click on + icon to translate published posts, I get a critical error message on my website.

![Translating](https://github.com/polylang/polylang/assets/112475805/f28f12fc-41ee-4084-aa65-87685cd6a3fe)

Refer to the error message:

`Fatal error: Uncaught Error: The script tried to modify a property on an incomplete object. Please ensure that the class definition "Wpil_Model_Link" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /var/www/wordpress/wp-includes/formatting.php:5058 Stack trace: #0 /var/www/wordpress/wp-includes/formatting.php(5053): map_deep() #1 /var/www/wordpress/wp-includes/formatting.php(2833): map_deep() #2 /var/www/wordpress/wp-includes/formatting.php(5711): stripslashes_deep() #3 /var/www/wordpress/wp-includes/meta.php(53): wp_unslash() #4 /var/www/wordpress/wp-content/plugins/polylang/modules/sync/sync-metas.php(379): add_metadata() #5 /var/www/wordpress/wp-content/plugins/polylang/modules/sync/admin-sync.php(107): PLL_Sync_Metas->copy() #6 /var/www/wordpress/wp-includes/class-wp-hook.php(310): PLL_Admin_Sync->new_post_translation() #7 /var/www/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters() #8 /var/www/wordpress/wp-includes/post.php(8108): apply_filters() #9 /var/www/wordpress/wp-admin/post-new.php(71): use_block_editor_for_post() #10 {main} thrown in /var/www/wordpress/wp-includes/formatting.php on line 5058`

![error](https://github.com/polylang/polylang/assets/112475805/562b44b3-7fa7-40a4-bf27-297a950ce1de)

There has been a critical error on this website. Please check your site admin email inbox for instructions.

Learn more about troubleshooting WordPress.

**Comment by Chouby** [comment]
It looks like the error is coming from a conflict with another plugin. Searching for "Wpil_Model_Link", I found out that is should come from "Link Whisper Free". See https://wpdirectory.net/search/01H2TGAF22SGE8M548T0P1NDP8

Without much investigation, it seems that this plugin stores an object in a post meta. When Polylang attempt to read this meta (to duplicate it in the new post translation), more specificallly, [to unserialize it](https://github.com/polylang/polylang/blob/3.4.2/modules/sync/sync-metas.php#L377), the object is not correctly created as the object class is not well defined. 

I invite you to contact the author of this plugin to inform him/her from the issue and him/her to apply the suggestion included in the error message
```Please ensure that the class definition "Wpil_Model_Link" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition
```
