### ISSUE TITLE
PHP 8.1 - another one for array_keys

### ISSUE THREAD

**Issue by dereckson** [polylang/polylang#986]
When wp-cron.php fire the do_pings action, this occurs under PHP 8.1:

```
[22-Feb-2022 13:56:59 UTC] PHP Fatal error:  Uncaught TypeError: array_keys():
Argument #1 ($array) must be of type array, bool given
in /srv/wordpress/wp -content/plugins/polylang/modules/sync/sync-post-metas.php:54

Stack trace:
#0 /srv/wordpress/wp-content/plugins/polylang/modules/sync/sync-post-metas.php(54): array_keys(false)
#1 /srv/wordpress/wp-content/plugins/polylang/modules/sync/sync-metas.php(299): PLL_Sync_Post_Metas->get_metas_to_copy(129, 0, 'fr', true)
#2 /srv/wordpress/wp-includes/class-wp-hook.php(309): PLL_Sync_Metas->store_metas_to_sync(Array, 129)
#3 /srv/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /srv/wordpress/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /srv/wordpress/wp-includes/meta.php(476): do_action('delete_post_met...', Array, 129, '_pingme', '')
#6 /srv/wordpress/wp-includes/post.php(2484): delete_metadata('post', 129, '_pingme', '')
#7 /srv/wordpress/wp-includes/comment.php(2858): delete_post_meta(129, '_pingme')
#8 /srv/wordpress/wp-includes/class-wp-hook.php(305): do_all_pingbacks()
```

**Comment by Chouby** [comment]
Thank you for the bug report.
Note for ourselves: we should use `get_post_custom_keys()` instead of `get_post_custom()`. Beware that this function returns `array|void`.
